// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// SCAFFOLD generated by the Validator Agent (attack A2d45a6a71b).
// Implement the protocol deployment + the entry invocation below.
// Everything the engine knows about the attack is in the TODO lines.
//
//   entry point:      contracts/contract/megapool/RocketMegapoolDelegate.sol#21639::assignFunds#20004
//   controlled input: _validatorId, msg.value
//   probed asset:     the asset the delta check measures
//   cross assets:     none recorded
//   attacker setup:   Deploy an attacker contract (or use an EOA) as the caller.

contract contracts_contract_megapool_RocketMegapoolDelegate_solHarness {
    // TODO: deploy the protocol (or attach to fork addresses) and fund it

    function setup() external {
        // TODO: deploy/fund; ensure the protocol account holds the probed
        // asset and the cross assets before returning
    }

    function protocolAccount() external view returns (address) {
        // TODO: return the protocol's asset-holding account
        return address(this);
    }

    function performAttack(address attacker)
        external returns (bool ok, bytes memory ret)
    {
        // TODO: invoke the entry point with attacker-chosen inputs
        // (attacker is the GenericAttacker: spender + callback receiver)
        // and return the raw call result:
        //   (ok, ret) = entry.someCall(abi.encode(..., attacker, ...));
        return (false, "");
    }

    function probedAsset() external view returns (address) {
        // TODO: return the token address whose balance the bracketing
        // check measures
        return address(0);
    }

    function probedAssetBalance(address who) external view returns (uint256) {
        // TODO: balance of the probed asset for `who`
        return 0;
    }

    function crossAssetCount() external view returns (uint256) {
        // TODO: number of other contract-held assets to watch
        return 0;
    }

    function crossAssetAt(uint256) external view returns (address) {
        // TODO: i-th cross asset address
        return address(0);
    }

    function crossAssetHeldBy(address, address) external view returns (uint256) {
        // TODO: holdings of a cross asset for an account
        return 0;
    }
}
