"""Foundry test synthesis from an attack hypothesis.

Division of responsibility (keeps the engine generic):

  ENGINE (this module) generates, purely from the attack record:
    - the IProtocolHarness interface (setup + entry invocation contract)
    - a generic attacker contract: plays the approved-spender role and
      the callback-receiver role (ERC-721/1155 hooks) that drains the
      probed asset when a cross asset lands on it
    - the test driver with exactly two executable questions:
        test_attack_call_succeeds : did the attack sequence complete
                                    (confirm precondition)?
        test_attacker_gains       : did the attacker end up with the
                                    probed asset or a cross asset?
      both pass -> CONFIRM; a failure is an executed REJECT reason
    - a harness SCAFFOLD (with the attack's own data filling the TODO
      lines) when no harness was supplied

  HARNESS (supplied as DATA per repository) implements IProtocolHarness:
  protocol deployment, funding, and the entry invocation with attacker-
  chosen inputs. Nothing in the engine knows any protocol name.

Only generic token-standard vocabulary (IERC20 / receiver hooks) and the
canonical Foundry cheatcode address appear in generated code.
"""

from __future__ import annotations

import re
from typing import Any

CHEATCODE_ADDRESS = "0x7109709ECfa91a80626fF3989D68f67F5b1DD12D"


def test_slug(attack_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", attack_id) or "Attack"


def render_test(attack: dict[str, Any], harness_contract: str,
                harness_file: str = "") -> str:
    """Render the Foundry test file for one attack."""
    slug = test_slug(attack.get("attack_id", ""))
    plan = attack.get("validator_plan") or {}
    consequence = attack.get("expected_consequence") or {}
    blind = consequence.get("cross_asset_blind_spot") or {}
    has_cross = bool(blind.get("other_assets"))

    gain_check = _GAIN_WITH_CROSS if has_cross else _GAIN_PROBED_ONLY
    harness_import = (
        f'import {{{harness_contract}}} from "./{harness_file}";'
        if harness_file else ""
    )

    return _TEST_TEMPLATE.format(
        slug=slug,
        harness=harness_contract,
        harness_import=harness_import,
        cheatcode=CHEATCODE_ADDRESS,
        gain_check=gain_check,
        confirm_if=_escape(plan.get("confirm_if", "")),
        reject_if=_escape(plan.get("reject_if", "")),
        probed_asset=_escape(blind.get("probed_asset", "probed asset")),
        cross_names=_escape(", ".join(blind.get("other_assets") or [])),
    )


def _escape(text: str) -> str:
    return (text or "").replace("\\", "\\\\").replace('"', '\\"')


_TEST_TEMPLATE = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// AUTO-GENERATED by the Validator Agent from attack {slug}.
// Engine-generated, protocol-agnostic: all protocol specifics live in the
// supplied {harness} harness (IProtocolHarness).
//
// CONFIRM condition under test: "{confirm_if}"
// REJECT condition:            "{reject_if}"

{harness_import}

interface Vm {{
    function startPrank(address) external;
    function stopPrank() external;
    function prank(address) external;
    function label(address, string calldata) external;
    function deal(address, uint256) external;
}}

interface IERC20Minimal {{
    function balanceOf(address) external view returns (uint256);
    function transferFrom(address, address, uint256) external returns (bool);
    function allowance(address, address) external view returns (uint256);
}}

interface IERC721ReceiverMinimal {{
    function onERC721Received(address, address, uint256, bytes calldata)
        external returns (bytes4);
}}

/// Supplied per-repository harness: deploys/funds the protocol and
/// performs the entry invocation with attacker-chosen inputs.
interface IProtocolHarness {{
    function setup() external;
    function protocolAccount() external view returns (address);
    function performAttack(address attacker) external returns (bool ok, bytes memory ret);
    function probedAsset() external view returns (address);
    function probedAssetBalance(address who) external view returns (uint256);
    function crossAssetCount() external view returns (uint256);
    function crossAssetAt(uint256 i) external view returns (address);
    function crossAssetHeldBy(address asset, address who) external view returns (uint256);
    
    // Extended interface for new test patterns
    function gasLimitThreshold() external view returns (uint256);
    function performVictimAction() external returns (bool);
    function getRandomnessOutcome() external view returns (uint256);
    function getExpectedMean() external view returns (uint256);
}}

/// Generic attacker: approved-spender + callback-receiver. When a cross
/// asset lands on it (safe-transfer hook) it drains the probed asset
/// from the protocol account through the granted allowance.
contract GenericAttacker {{
    IProtocolHarness internal harness;
    IERC20Minimal internal probed;

    constructor(IProtocolHarness h) {{
        harness = h;
        probed = IERC20Minimal(h.probedAsset());
    }}

    function drainProtocol() external {{
        _drain();
    }}

    function _drain() internal {{
        address protocol = harness.protocolAccount();
        uint256 allowance = probed.allowance(protocol, address(this));
        if (allowance == 0) return;
        uint256 amount = probed.balanceOf(protocol);
        if (amount > allowance) amount = allowance;
        if (amount > 0) probed.transferFrom(protocol, address(this), amount);
    }}

    function onERC721Received(address, address, uint256, bytes calldata)
        external returns (bytes4)
    {{
        _drain();
        return this.onERC721Received.selector;
    }}

    function onERC1155Received(address, address, uint256, uint256, bytes calldata)
        external returns (bytes4)
    {{
        _drain();
        return this.onERC1155Received.selector;
    }}

    function supportsInterface(bytes4 interfaceId) external pure returns (bool) {{
        return interfaceId == 0x150b7a02 || interfaceId == 0x01ffc9a7;
    }}
}}

contract Validate{slug} {{
    Vm internal constant vm = Vm({cheatcode});

    IProtocolHarness internal harness;
    GenericAttacker internal attacker;

    event AttackOutcome(bool ok, bytes ret);
    event Balances(uint256 probedBefore, uint256 probedAfter, uint256 crossAfter);

    function setUp() public {{
        harness = IProtocolHarness(address(new {harness}()));
        harness.setup();
        attacker = new GenericAttacker(harness);
        vm.label(address(attacker), "attacker");
    }}

    /// Question 1: does the attack sequence complete (check passes /
    /// call succeeds)? Failing here is an executed REJECT reason.
    function test_attack_call_succeeds() public {{
        (bool ok, bytes memory ret) = harness.performAttack(address(attacker));
        emit AttackOutcome(ok, ret);
        require(ok, "attack call reverted: path blocked or preconditions unmet");
    }}

    /// Question 2: does the attacker gain the probed asset or a cross
    /// asset? Failing here is an executed REJECT reason (check holds).
    function test_attacker_gains() public {{
        uint256 probedBefore = harness.probedAssetBalance(address(attacker));
        (bool ok, bytes memory ret) = harness.performAttack(address(attacker));
        require(ok, "attack call reverted");
        emit AttackOutcome(ok, ret);
        uint256 probedAfter = harness.probedAssetBalance(address(attacker));
{gain_check}
        emit Balances(probedBefore, probedAfter, crossAfter);
        require(gained, "attacker gained nothing: confirm condition disproved");
    }}

    /// Question 3: does operation exceed gas limit? (for gas DoS attacks)
    /// Failing here (gas > threshold) is a CONFIRM reason.
    /// Note: Only runs if harness implements gasLimitThreshold()
    function test_gas_consumption_within_limits() public {{
        // Try to get threshold, default to 25M if not implemented
        uint256 threshold = 25_000_000; // Base chain block gas limit
        try harness.gasLimitThreshold() returns (uint256 t) {{
            if (t > 0) threshold = t;
        }} catch {{
            // Harness doesn't implement this - use default
        }}
        
        uint256 gasBefore = gasleft();
        try harness.performAttack(address(attacker)) {{
            uint256 gasUsed = gasBefore - gasleft();
            require(gasUsed < threshold, "Gas DoS: excessive consumption exceeds block limit");
        }} catch {{
            // Attack reverted - not a gas DoS issue
        }}
    }}

    /// Question 4: does arithmetic operation overflow/panic? (for arithmetic bound violations)
    /// Panic code 0x11 (arithmetic overflow) or 0x01 (assertion) means CONFIRM.
    function test_arithmetic_bounds_respected() public {{
        (bool ok, bytes memory err) = harness.performAttack(address(attacker));
        
        // If call succeeded, bounds were not enforced (potential vulnerability)
        if (ok) return;
        
        // If reverted, check if it was due to panic (overflow/underflow)
        if (err.length >= 4) {{
            bytes4 selector;
            assembly {{ selector := mload(add(err, 0x20)) }}
            
            // Panic selector is 0x4e487b71
            if (selector == 0x4e487b71) {{
                // Extract panic code
                require(false, "Panic: arithmetic overflow/underflow detected - bounds violated");
            }}
        }}
    }}

    /// Question 5: can attacker frontrun critical operation? (for frontrun attacks)
    /// Victim tx failing after attacker manipulation means CONFIRM.
    /// Note: Only runs if harness implements performVictimAction()
    function test_state_race_protected() public {{
        address victim = address(0xbeef);
        vm.deal(victim, 100 ether);
        
        // Attacker frontruns with state manipulation
        vm.prank(address(attacker));
        try harness.performAttack(address(attacker)) {{
            // Victim transaction attempts to execute
            vm.prank(victim);
            try harness.performVictimAction() returns (bool victimSuccess) {{
                require(victimSuccess, "Frontrun succeeded: victim transaction blocked");
            }} catch {{
                // Harness doesn't implement this method - skip test
                return;
            }}
        }} catch {{
            // Attack reverted - not exploitable
        }}
    }}

    /// Question 6: does randomness distribution show bias? (for statistical exploits)
    /// Statistical deviation beyond tolerance means CONFIRM.
    /// Note: Only runs if harness implements randomness methods
    function test_randomness_distribution_fair() public {{
        uint256 trials = 100;
        uint256 sum = 0;
        
        // Try to run statistical test if harness supports it
        try harness.getExpectedMean() returns (uint256 expectedMean) {{
            if (expectedMean == 0) return; // Not implemented
            
            for (uint256 i = 0; i < trials; i++) {{
                harness.setup(); // Reset state
                try harness.performAttack(address(attacker)) {{
                    try harness.getRandomnessOutcome() returns (uint256 outcome) {{
                        sum += outcome;
                    }} catch {{
                        return; // Method not implemented
                    }}
                }} catch {{
                    // Attack failed - skip trial
                }}
            }}
            
            uint256 actualMean = sum / trials;
            uint256 deviation = actualMean > expectedMean 
                ? actualMean - expectedMean 
                : expectedMean - actualMean;
            
            // Allow 10% deviation tolerance
            uint256 tolerance = expectedMean / 10;
            require(deviation <= tolerance, "Statistical bias detected in randomness");
        }} catch {{
            // Harness doesn't implement randomness testing - skip
            return;
        }}
    }}
}}
"""

_GAIN_WITH_CROSS = """        uint256 crossAfter = 0;
        for (uint256 i = 0; i < harness.crossAssetCount(); i++) {{
            address asset = harness.crossAssetAt(i);
            crossAfter += harness.crossAssetHeldBy(asset, address(attacker));
        }}
        bool gained = probedAfter > probedBefore || crossAfter > 0;"""

_GAIN_PROBED_ONLY = """        uint256 crossAfter = 0;
        bool gained = probedAfter > probedBefore;"""


def render_harness_scaffold(attack: dict[str, Any], harness_name: str) -> str:
    """Scaffold for a missing harness, pre-filled with the attack's own
    data (entry point, controlled inputs, probed asset, cross assets) so
    a human/orchestrator only fills the protocol plumbing."""
    slug = test_slug(attack.get("attack_id", ""))
    entry = attack.get("entry_point", {}).get("function", "?")
    inputs = ", ".join(
        i.get("expression", "?") for i in attack.get("controlled_inputs", [])
    ) or "none recorded"
    blind = (attack.get("expected_consequence") or {}).get("cross_asset_blind_spot") or {}
    probed = blind.get("probed_asset", "the asset the delta check measures")
    cross = ", ".join(blind.get("other_assets") or []) or "none recorded"
    plan = attack.get("validator_plan") or {}

    return _SCAFFOLD_TEMPLATE.format(
        name=harness_name,
        slug=slug,
        entry=_escape(entry),
        inputs=_escape(inputs),
        probed=_escape(str(probed)),
        cross=_escape(cross),
        attacker_setup=_escape(plan.get("attacker_setup", "")),
    )


_SCAFFOLD_TEMPLATE = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// SCAFFOLD generated by the Validator Agent (attack {slug}).
// Implement the protocol deployment + the entry invocation below.
// Everything the engine knows about the attack is in the TODO lines.
//
//   entry point:      {entry}
//   controlled input: {inputs}
//   probed asset:     {probed}
//   cross assets:     {cross}
//   attacker setup:   {attacker_setup}

contract {name} {{
    // TODO: deploy the protocol (or attach to fork addresses) and fund it

    function setup() external {{
        // TODO: deploy/fund; ensure the protocol account holds the probed
        // asset and the cross assets before returning
    }}

    function protocolAccount() external view returns (address) {{
        // TODO: return the protocol's asset-holding account
        return address(this);
    }}

    function performAttack(address attacker)
        external returns (bool ok, bytes memory ret)
    {{
        // TODO: invoke the entry point with attacker-chosen inputs
        // (attacker is the GenericAttacker: spender + callback receiver)
        // and return the raw call result:
        //   (ok, ret) = entry.someCall(abi.encode(..., attacker, ...));
        return (false, "");
    }}

    function probedAsset() external view returns (address) {{
        // TODO: return the token address whose balance the bracketing
        // check measures
        return address(0);
    }}

    function probedAssetBalance(address who) external view returns (uint256) {{
        // TODO: balance of the probed asset for `who`
        return 0;
    }}

    function crossAssetCount() external view returns (uint256) {{
        // TODO: number of other contract-held assets to watch
        return 0;
    }}

    function crossAssetAt(uint256) external view returns (address) {{
        // TODO: i-th cross asset address
        return address(0);
    }}

    function crossAssetHeldBy(address, address) external view returns (uint256) {{
        // TODO: holdings of a cross asset for an account
        return 0;
    }}
}}
"""
